# Generated by Django 3.2 on 2021-04-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('A', 'Administrator'), ('P', 'Professor'), ('T', 'Ta')], default='A', max_length=1)),
                ('phoneNumber', models.IntegerField()),
                ('homeAddress', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='final_project.user')),
                ('title', models.CharField(max_length=40)),
            ],
            bases=('final_project.user',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='final_project.user')),
                ('coursesTaught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='final_project.course')),
            ],
            bases=('final_project.user',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='final_project.instructor')),
            ],
            bases=('final_project.instructor',),
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='final_project.instructor')),
                ('skills', models.CharField(max_length=75)),
            ],
            bases=('final_project.instructor',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionID', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project.course')),
                ('taID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='final_project.ta')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureID', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project.course')),
                ('profID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='final_project.professor')),
                ('taID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='final_project.ta')),
            ],
        ),
    ]
